# Generated by Django 4.0.6 on 2022-08-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_movie_poster_movie_published_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
