# Generated by Django 4.0.6 on 2022-08-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_movie_published_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.FileField(blank=True, upload_to='movie/static/movie/img'),
        ),
    ]
