# Generated by Django 4.0.6 on 2022-08-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_movie_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.FileField(blank=True, upload_to='movie/img'),
        ),
    ]
